
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package compi2.valitationsej.analysis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BTRUE = 11;
  public static final int STRING_LIT = 21;
  public static final int DEC_I = 16;
  public static final int CADENA = 17;
  public static final int BFALSE = 12;
  public static final int IGUAL = 10;
  public static final int FLOAT_I = 15;
  public static final int ID = 20;
  public static final int POR = 9;
  public static final int PARENTESIS_R = 7;
  public static final int COMA = 3;
  public static final int PARENTESIS_L = 6;
  public static final int CORCHETE_R = 5;
  public static final int EOF = 0;
  public static final int INTEGER_LIT = 23;
  public static final int CORCHETE_L = 4;
  public static final int error = 1;
  public static final int BOOL_I = 13;
  public static final int FLOAT_LIT = 22;
  public static final int FIN = 2;
  public static final int INT_I = 14;
  public static final int VECTORS = 19;
  public static final int MAS = 8;
  public static final int UMINUS = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FIN",
  "COMA",
  "CORCHETE_L",
  "CORCHETE_R",
  "PARENTESIS_L",
  "PARENTESIS_R",
  "MAS",
  "POR",
  "IGUAL",
  "BTRUE",
  "BFALSE",
  "BOOL_I",
  "INT_I",
  "FLOAT_I",
  "DEC_I",
  "CADENA",
  "UMINUS",
  "VECTORS",
  "ID",
  "STRING_LIT",
  "FLOAT_LIT",
  "INTEGER_LIT"
  };
}

